import { Routes } from '@angular/router';
import { Layout } from './layout/layout';
import { authGuard, adminGuard } from './guards/auth.guard';

export const routes: Routes = [
  {
    path: '',
    component: Layout,
    children: [
      // Public
      { path: '', loadComponent: () => import('./news/news').then(m => m.News) },
      { path: 'login', loadComponent: () => import('./pages/login/login').then(m => m.LoginPage) },
      { path: 'register', loadComponent: () => import('./pages/register/register').then(m => m.RegisterPage) },
      { path: 'about', loadComponent: () => import('./pages/about/about').then(m => m.AboutPage) },
      { path: 'contact', loadComponent: () => import('./pages/contact/contact').then(m => m.ContactPage) },

      // Public live views
      { path: 'rebotling/live', loadComponent: () => import('./pages/rebotling-live/rebotling-live').then(m => m.RebotlingLivePage) },
      { path: 'rebotling/live-ranking', loadComponent: () => import('./pages/live-ranking/live-ranking').then(m => m.LiveRankingPage) },
      { path: 'tvattlinje/live', loadComponent: () => import('./pages/tvattlinje-live/tvattlinje-live').then(m => m.TvattlinjeLivePage) },
      { path: 'saglinje/live', loadComponent: () => import('./pages/saglinje-live/saglinje-live').then(m => m.SaglinjeLivePage) },
      { path: 'klassificeringslinje/live', loadComponent: () => import('./pages/klassificeringslinje-live/klassificeringslinje-live').then(m => m.KlassificeringslinjeLivePage) },

      // Public reports/stats
      { path: 'rebotling/skiftrapport', loadComponent: () => import('./pages/rebotling-skiftrapport/rebotling-skiftrapport').then(m => m.RebotlingSkiftrapportPage) },
      { path: 'rebotling/statistik', loadComponent: () => import('./pages/rebotling/rebotling-statistik').then(m => m.RebotlingStatistikPage) },
      { path: 'rebotling/historik', loadComponent: () => import('./pages/historik/historik').then(m => m.HistorikPage) },
      { path: 'rebotling/narvarotracker', loadComponent: () => import('./pages/rebotling/narvarotracker/narvarotracker').then(m => m.NarvarotrackerPage) },
      { path: 'rebotling/produktionspuls', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionspuls/produktionspuls').then(m => m.ProduktionspulsPage) },
      { path: 'rebotling/benchmarking', canActivate: [authGuard], loadComponent: () => import('./pages/benchmarking/benchmarking').then(m => m.BenchmarkingPage) },
      { path: 'tvattlinje/skiftrapport', loadComponent: () => import('./pages/tvattlinje-skiftrapport/tvattlinje-skiftrapport').then(m => m.TvattlinjeSkiftrapportPage) },
      { path: 'tvattlinje/statistik', loadComponent: () => import('./pages/tvattlinje-statistik/tvattlinje-statistik').then(m => m.TvattlinjeStatistikPage) },
      { path: 'saglinje/skiftrapport', loadComponent: () => import('./pages/saglinje-skiftrapport/saglinje-skiftrapport').then(m => m.SaglinjeSkiftrapportPage) },
      { path: 'saglinje/statistik', loadComponent: () => import('./pages/saglinje-statistik/saglinje-statistik').then(m => m.SaglinjeStatistikPage) },
      { path: 'klassificeringslinje/skiftrapport', loadComponent: () => import('./pages/klassificeringslinje-skiftrapport/klassificeringslinje-skiftrapport').then(m => m.KlassificeringslinjeSkiftrapportPage) },
      { path: 'klassificeringslinje/statistik', loadComponent: () => import('./pages/klassificeringslinje-statistik/klassificeringslinje-statistik').then(m => m.KlassificeringslinjeStatistikPage) },

      // Rapporter
      { path: 'rapporter/manad', canActivate: [authGuard], loadComponent: () => import('./pages/monthly-report/monthly-report').then(m => m.MonthlyReportPage) },
      { path: 'rapporter/vecka', canActivate: [authGuard], loadComponent: () => import('./pages/weekly-report/weekly-report').then(m => m.WeeklyReportPage) },

      // Authenticated routes
      { path: 'rebotling/min-dag', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/min-dag/min-dag').then(m => m.MinDagPage) },
      { path: 'rebotling/kassationsanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationsanalys/kassationsanalys').then(m => m.KassationsanalysPage) },
      { path: 'rebotling/cykeltid-heatmap', canActivate: [authGuard], loadComponent: () => import('./pages/cykeltid-heatmap/cykeltid-heatmap').then(m => m.CykeltidHeatmapComponent) },
      { path: 'rebotling/produkttyp-effektivitet', loadComponent: () => import('./pages/statistik-produkttyp-effektivitet/statistik-produkttyp-effektivitet').then(m => m.StatistikProduktTypEffektivitetComponent) },
      { path: 'rebotling/alerts', canActivate: [adminGuard], loadComponent: () => import('./pages/rebotling/alerts/alerts').then(m => m.AlertsPage) },
      { path: 'min-bonus', canActivate: [authGuard], loadComponent: () => import('./pages/my-bonus/my-bonus').then(m => m.MyBonusPage) },
      { path: 'rebotling/overlamning', canActivate: [authGuard], loadComponent: () => import('./pages/shift-handover/shift-handover').then(m => m.ShiftHandoverPage) },
      { path: 'rebotling/skiftoverlamning', canActivate: [authGuard], loadComponent: () => import('./pages/skiftoverlamning/skiftoverlamning').then(m => m.SkiftoverlamningPage) },
      { path: 'stopporsaker', canActivate: [authGuard], loadComponent: () => import('./pages/stoppage-log/stoppage-log').then(m => m.StoppageLogPage) },
      { path: 'rebotling/stopporsak-registrering', canActivate: [authGuard], loadComponent: () => import('./pages/stopporsak-registrering/stopporsak-registrering').then(m => m.StopporsakRegistreringPage) },
      { path: 'rebotling/underhallslogg', canActivate: [authGuard], loadComponent: () => import('./pages/underhallslogg/underhallslogg').then(m => m.UnderhallsloggComponent) },
      { path: 'rebotling/oee-benchmark', canActivate: [authGuard], loadComponent: () => import('./pages/oee-benchmark/oee-benchmark').then(m => m.OeeBenchmarkComponent) },
      { path: 'rebotling/skiftrapport-export', canActivate: [authGuard], loadComponent: () => import('./pages/skiftrapport-export/skiftrapport-export').then(m => m.SkiftrapportExportComponent) },
      { path: 'rebotling/feedback-analys', canActivate: [authGuard], loadComponent: () => import('./pages/feedback-analys/feedback-analys').then(m => m.FeedbackAnalysComponent) },
      { path: 'rebotling/ranking-historik', canActivate: [authGuard], loadComponent: () => import('./pages/ranking-historik/ranking-historik').then(m => m.RankingHistorikComponent) },
      { path: 'rebotling/daglig-sammanfattning', canActivate: [authGuard], loadComponent: () => import('./pages/daglig-sammanfattning/daglig-sammanfattning').then(m => m.DagligSammanfattningComponent) },
      { path: 'rebotling/produktionskalender', canActivate: [authGuard], loadComponent: () => import('./pages/produktionskalender/produktionskalender').then(m => m.ProduktionskalenderComponent) },
      { path: 'rebotling/skiftjamforelse', canActivate: [authGuard], loadComponent: () => import('./pages/skiftjamforelse/skiftjamforelse').then(m => m.SkiftjamforelseComponent) },
      { path: 'rebotling/malhistorik', canActivate: [authGuard], loadComponent: () => import('./pages/malhistorik/malhistorik').then(m => m.MalhistorikComponent) },
      { path: 'rebotling/underhallsprognos', canActivate: [authGuard], loadComponent: () => import('./pages/underhallsprognos/underhallsprognos').then(m => m.UnderhallsprognosComponent) },
      { path: 'rebotling/effektivitet', canActivate: [authGuard], loadComponent: () => import('./pages/effektivitet/effektivitet').then(m => m.EffektivitetComponent) },
      { path: 'rebotling/produktionsmal', canActivate: [authGuard], loadComponent: () => import('./pages/produktionsmal/produktionsmal').then(m => m.ProduktionsmalComponent) },
      { path: 'rebotling/utnyttjandegrad', canActivate: [authGuard], loadComponent: () => import('./pages/utnyttjandegrad/utnyttjandegrad').then(m => m.UtnyttjandegradComponent) },
      { path: 'rebotling/produktionstakt', loadComponent: () => import('./pages/rebotling/produktionstakt/produktionstakt').then(m => m.ProduktionsTaktPage) },
      { path: 'rebotling/veckorapport', canActivate: [authGuard], loadComponent: () => import('./pages/veckorapport/veckorapport').then(m => m.VeckorapportPage) },
      { path: 'rebotling/alarm-historik', canActivate: [authGuard], loadComponent: () => import('./pages/alarm-historik/alarm-historik').then(m => m.AlarmHistorikPage) },
      { path: 'rebotling/operatorsportal', canActivate: [authGuard], loadComponent: () => import('./pages/operatorsportal/operatorsportal').then(m => m.OperatorsportalPage) },
      { path: 'rebotling/produktions-heatmap', canActivate: [authGuard], loadComponent: () => import('./pages/heatmap/heatmap').then(m => m.HeatmapPage) },
      { path: 'rebotling/pareto', canActivate: [authGuard], loadComponent: () => import('./pages/pareto/pareto').then(m => m.ParetoPage) },
      { path: 'rebotling/oee-waterfall', canActivate: [authGuard], loadComponent: () => import('./pages/oee-waterfall/oee-waterfall').then(m => m.OeeWaterfallPage) },
      { path: 'rebotling/morgonrapport', canActivate: [authGuard], loadComponent: () => import('./pages/morgonrapport/morgonrapport').then(m => m.MorgonrapportPage) },
      { path: 'rebotling/drifttids-timeline', canActivate: [authGuard], loadComponent: () => import('./pages/drifttids-timeline/drifttids-timeline.component').then(m => m.DrifttidsTimelineComponent) },
      { path: 'rebotling/kassationsorsak-drilldown', canActivate: [authGuard], loadComponent: () => import('./pages/kassations-drilldown/kassations-drilldown').then(m => m.KassationsDrilldownPage) },
      { path: 'rebotling/forsta-timme-analys', canActivate: [authGuard], loadComponent: () => import('./pages/forsta-timme-analys/forsta-timme-analys').then(m => m.ForstaTimmeAnalysPage) },
      { path: 'rebotling/operator-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/operator-personal-dashboard/operator-personal-dashboard').then(m => m.OperatorPersonalDashboardPage) },
      { path: 'rebotling/produktionsprognos', canActivate: [authGuard], loadComponent: () => import('./pages/produktionsprognos/produktionsprognos').then(m => m.ProduktionsPrognosPage) },
      { path: 'rebotling/stopporsak-operator', canActivate: [authGuard], loadComponent: () => import('./pages/stopporsak-operator/stopporsak-operator').then(m => m.StopporsakOperatorPage) },
      { path: 'rebotling/operator-onboarding', canActivate: [authGuard], loadComponent: () => import('./pages/operator-onboarding/operator-onboarding').then(m => m.OperatorOnboardingPage) },
      { path: 'rebotling/operator-jamforelse', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/operator-jamforelse/operator-jamforelse').then(m => m.OperatorJamforelsePage) },
      { path: 'favoriter', canActivate: [authGuard], loadComponent: () => import('./pages/favoriter/favoriter').then(m => m.FavoriterPage) },
      { path: 'rebotling/produktionseffektivitet', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionseffektivitet/produktionseffektivitet').then(m => m.ProduktionseffektivitetPage) },
      { path: 'rebotling/kvalitets-trendbrott', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kvalitets-trendbrott/kvalitets-trendbrott').then(m => m.KvalitetsTrendbrottPage) },
      { path: 'rebotling/maskinunderhall', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskinunderhall/maskinunderhall.component').then(m => m.MaskinunderhallPage) },
      { path: 'rebotling/statistik-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/statistik-dashboard/statistik-dashboard.component').then(m => m.StatistikDashboardPage) },
      { path: 'rebotling/batch-sparning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/batch-sparning/batch-sparning.component').then(m => m.BatchSparningPage) },
      { path: 'rebotling/kassationsorsak-statistik', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationsorsak-statistik/kassationsorsak-statistik').then(m => m.KassationsorsakStatistikPage) },
      { path: 'rebotling/produktions-sla', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktions-sla/produktions-sla.component').then(m => m.ProduktionsSlaPage) },
      { path: 'rebotling/skiftplanering', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/skiftplanering/skiftplanering.component').then(m => m.SkiftplaneringPage) },
      { path: 'rebotling/produktionskostnad', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionskostnad/produktionskostnad.component').then(m => m.ProduktionskostnadPage) },
      { path: 'rebotling/stopptidsanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/stopptidsanalys/stopptidsanalys.component').then(m => m.StopptidsanalysPage) },
      { path: 'rebotling/maskin-oee', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskin-oee/maskin-oee.component').then(m => m.MaskinOeePage) },
      { path: 'rebotling/operatorsbonus', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/operatorsbonus/operatorsbonus.component').then(m => m.OperatorsbonusPage) },
      { path: 'rebotling/leveransplanering', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/leveransplanering/leveransplanering.component').then(m => m.LeveransplaneringPage) },
      { path: 'rebotling/kvalitetscertifikat', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kvalitetscertifikat/kvalitetscertifikat.component').then(m => m.KvalitetscertifikatPage) },
      { path: 'rebotling/historisk-produktion', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/historisk-produktion/historisk-produktion.component').then(m => m.HistoriskProduktionPage) },
      { path: 'rebotling/avvikelselarm', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/avvikelselarm/avvikelselarm.component').then(m => m.AvvikelselarmPage) },
      { path: 'rebotling/sammanfattning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/rebotling-sammanfattning/rebotling-sammanfattning.component').then(m => m.RebotlingSammanfattningPage) },
      { path: 'rebotling/produktionsflode', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionsflode/produktionsflode.component').then(m => m.ProduktionsflodePage) },
      { path: 'rebotling/kassationsorsak', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationsorsak/kassationsorsak').then(m => m.KassationsorsakPage) },
      { path: 'rebotling/oee-jamforelse', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/oee-jamforelse/oee-jamforelse').then(m => m.OeeJamforelsePage) },
      { path: 'rebotling/maskin-drifttid', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskin-drifttid/maskin-drifttid').then(m => m.MaskinDrifttidPage) },
      { path: 'rebotling/skiftrapport-sammanstallning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/skiftrapport-sammanstallning/skiftrapport-sammanstallning').then(m => m.SkiftrapportSammanstallningPage) },
      { path: 'rebotling/maskinhistorik', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskinhistorik/maskinhistorik.component').then(m => m.MaskinhistorikPage) },
      { path: 'rebotling/kassationskvot-alarm', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationskvot-alarm/kassationskvot-alarm.component').then(m => m.KassationskvotAlarmPage) },
      { path: 'rebotling/produktions-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktions-dashboard/produktions-dashboard.component').then(m => m.ProduktionsDashboardPage) },
      { path: 'rebotling/kapacitetsplanering', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kapacitetsplanering/kapacitetsplanering.component').then(m => m.KapacitetsplaneringPage) },
      { path: 'rebotling/rebotling-trendanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/rebotling-trendanalys/rebotling-trendanalys.component').then(m => m.RebotlingTrendanalysPage) },
      { path: 'rebotling/operators-prestanda', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/operators-prestanda/operators-prestanda.component').then(m => m.OperatorsPrestandaPage) },
      { path: 'rebotling/stationsdetalj', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/stationsdetalj/stationsdetalj.component').then(m => m.RebotlingStationsdetaljPage) },
      { path: 'rebotling/vd-veckorapport', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/vd-veckorapport/vd-veckorapport.component').then(m => m.VdVeckorapportPage) },
      { path: 'rebotling/stopporsaker', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/stopporsaker/stopporsaker.component').then(m => m.StopporsakerPage) },
      { path: 'rebotling/produktionsmal-uppfoljning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionsmal/produktionsmal.component').then(m => m.RebotlingProduktionsmalPage) },
      { path: 'rebotling/tidrapport', canActivate: [authGuard], loadComponent: () => import('./pages/tidrapport/tidrapport.component').then(m => m.TidrapportPage) },
      { path: 'rebotling/oee-trendanalys', canActivate: [authGuard], loadComponent: () => import('./pages/oee-trendanalys/oee-trendanalys.component').then(m => m.OeeTrendanalysPage) },
      { path: 'rebotling/operator-ranking', canActivate: [authGuard], loadComponent: () => import('./pages/operator-ranking/operator-ranking.component').then(m => m.OperatorRankingPage) },
      { path: 'rebotling/vd-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/vd-dashboard/vd-dashboard.component').then(m => m.VdDashboardPage) },
      { path: 'rebotling/historisk-sammanfattning', canActivate: [authGuard], loadComponent: () => import('./pages/historisk-sammanfattning/historisk-sammanfattning.component').then(m => m.HistoriskSammanfattningPage) },

      // Admin routes
      { path: 'oversikt', canActivate: [adminGuard], loadComponent: () => import('./pages/executive-dashboard/executive-dashboard').then(m => m.ExecutiveDashboardPage) },
      { path: 'rebotling/admin', canActivate: [adminGuard], loadComponent: () => import('./pages/rebotling-admin/rebotling-admin').then(m => m.RebotlingAdminPage) },
      { path: 'rebotling/bonus', canActivate: [adminGuard], loadComponent: () => import('./pages/bonus-dashboard/bonus-dashboard').then(m => m.BonusDashboardPage) },
      { path: 'rebotling/bonus-admin', canActivate: [adminGuard], loadComponent: () => import('./pages/bonus-admin/bonus-admin').then(m => m.BonusAdminPage) },
      { path: 'rebotling/analys', canActivate: [adminGuard], loadComponent: () => import('./pages/production-analysis/production-analysis').then(m => m.ProductionAnalysisPage) },
      { path: 'rebotling/kalender', canActivate: [adminGuard], loadComponent: () => import('./pages/production-calendar/production-calendar').then(m => m.ProductionCalendarPage) },
      { path: 'rebotling/prognos', canActivate: [adminGuard], loadComponent: () => import('./pages/rebotling-prognos/rebotling-prognos').then(m => m.RebotlingPrognosPage) },
      { path: 'tvattlinje/admin', canActivate: [adminGuard], loadComponent: () => import('./pages/tvattlinje-admin/tvattlinje-admin').then(m => m.TvattlinjeAdminPage) },
      { path: 'saglinje/admin', canActivate: [adminGuard], loadComponent: () => import('./pages/saglinje-admin/saglinje-admin').then(m => m.SaglinjeAdminPage) },
      { path: 'klassificeringslinje/admin', canActivate: [adminGuard], loadComponent: () => import('./pages/klassificeringslinje-admin/klassificeringslinje-admin').then(m => m.KlassificeringslinjeAdminPage) },
      { path: 'admin/users', canActivate: [adminGuard], loadComponent: () => import('./pages/users/users').then(m => m.UsersPage) },
      { path: 'admin/create-user', canActivate: [adminGuard], loadComponent: () => import('./pages/create-user/create-user').then(m => m.CreateUserPage) },
      { path: 'admin/vpn', canActivate: [adminGuard], loadComponent: () => import('./pages/vpn-admin/vpn-admin').then(m => m.VpnAdminPage) },
      { path: 'admin/audit', canActivate: [adminGuard], loadComponent: () => import('./pages/audit-log/audit-log').then(m => m.AuditLogPage) },
      { path: 'admin/news', canActivate: [adminGuard], loadComponent: () => import('./pages/news-admin/news-admin').then(m => m.NewsAdminPage) },
      { path: 'admin/operators', canActivate: [adminGuard], loadComponent: () => import('./pages/operators/operators').then(m => m.OperatorsPage) },
      { path: 'admin/skiftplan', canActivate: [adminGuard], loadComponent: () => import('./pages/shift-plan/shift-plan').then(m => m.ShiftPlanPage) },
      { path: 'admin/certifiering', canActivate: [adminGuard], loadComponent: () => import('./pages/certifications/certifications').then(m => m.CertificationsPage) },
      { path: 'admin/operator-dashboard', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-dashboard/operator-dashboard').then(m => m.OperatorDashboardPage) },
      { path: 'admin/operator-compare', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-compare/operator-compare').then(m => m.OperatorComparePage) },
      { path: 'admin/operator-attendance', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-attendance/operator-attendance').then(m => m.OperatorAttendancePage) },
      { path: 'admin/operator-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-trend/operator-trend').then(m => m.OperatorTrendPage) },
      { path: 'admin/kvalitetstrend', canActivate: [adminGuard], loadComponent: () => import('./pages/kvalitetstrend/kvalitetstrend').then(m => m.KvalitetstrendComponent) },
      { path: 'admin/stopporsak-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/stopporsak-trend/stopporsak-trend').then(m => m.StopporsakTrendComponent) },
      { path: 'admin/operator/:id', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-detail/operator-detail').then(m => m.OperatorDetailPage) },
      { path: 'admin/underhall', canActivate: [adminGuard], loadComponent: () => import('./pages/maintenance-log/maintenance-log').then(m => m.MaintenanceLogPage) },

      { path: 'rebotling/andon', loadComponent: () => import('./pages/andon/andon').then(m => m.AndonPage) },
      { path: 'rebotling/andon-board', canActivate: [authGuard], loadComponent: () => import('./pages/andon-board/andon-board').then(m => m.AndonBoardComponent) },
      { path: '**', loadComponent: () => import('./pages/not-found/not-found').then(m => m.NotFoundPage) }
    ]
  }
];
