import { Routes } from '@angular/router';
import { Layout } from './layout/layout';
import { authGuard, adminGuard } from './guards/auth.guard';
import { pendingChangesGuard } from './guards/pending-changes.guard';

export const routes: Routes = [
  {
    path: '',
    component: Layout,
    children: [
      // Public
      { path: '', pathMatch: 'full', loadComponent: () => import('./news/news').then(m => m.News) },
      { path: 'login', loadComponent: () => import('./pages/login/login').then(m => m.LoginPage) },
      { path: 'register', loadComponent: () => import('./pages/register/register').then(m => m.RegisterPage) },
      { path: 'about', loadComponent: () => import('./pages/about/about').then(m => m.AboutPage) },
      { path: 'contact', loadComponent: () => import('./pages/contact/contact').then(m => m.ContactPage) },

      // Public live views
      { path: 'rebotling/live', loadComponent: () => import('./pages/rebotling-live/rebotling-live').then(m => m.RebotlingLivePage) },
      { path: 'rebotling/live-ranking', loadComponent: () => import('./pages/live-ranking/live-ranking').then(m => m.LiveRankingPage) },
      { path: 'rebotling/topplista', redirectTo: 'rebotling/live-ranking', pathMatch: 'full' },
      { path: 'tvattlinje/live', loadComponent: () => import('./pages/tvattlinje-live/tvattlinje-live').then(m => m.TvattlinjeLivePage) },
      { path: 'saglinje/live', loadComponent: () => import('./pages/saglinje-live/saglinje-live').then(m => m.SaglinjeLivePage) },
      { path: 'klassificeringslinje/live', loadComponent: () => import('./pages/klassificeringslinje-live/klassificeringslinje-live').then(m => m.KlassificeringslinjeLivePage) },

      // Public reports/stats
      { path: 'rebotling/skiftrapport', loadComponent: () => import('./pages/rebotling-skiftrapport/rebotling-skiftrapport').then(m => m.RebotlingSkiftrapportPage) },
      { path: 'rebotling/statistik', loadComponent: () => import('./pages/rebotling/rebotling-statistik').then(m => m.RebotlingStatistikPage) },
      { path: 'rebotling/historik', loadComponent: () => import('./pages/historik/historik').then(m => m.HistorikPage) },
      { path: 'rebotling/narvarotracker', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/narvarotracker/narvarotracker').then(m => m.NarvarotrackerPage) },
      { path: 'rebotling/produktionspuls', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionspuls/produktionspuls').then(m => m.ProduktionspulsPage) },
      { path: 'rebotling/benchmarking', canActivate: [authGuard], loadComponent: () => import('./pages/benchmarking/benchmarking').then(m => m.BenchmarkingPage) },
      { path: 'tvattlinje/skiftrapport', loadComponent: () => import('./pages/tvattlinje-skiftrapport/tvattlinje-skiftrapport').then(m => m.TvattlinjeSkiftrapportPage) },
      { path: 'tvattlinje/statistik', loadComponent: () => import('./pages/tvattlinje-statistik/tvattlinje-statistik').then(m => m.TvattlinjeStatistikPage) },
      { path: 'saglinje', redirectTo: 'saglinje/statistik', pathMatch: 'full' },
      { path: 'saglinje/skiftrapport', loadComponent: () => import('./pages/saglinje-skiftrapport/saglinje-skiftrapport').then(m => m.SaglinjeSkiftrapportPage) },
      { path: 'saglinje/statistik', loadComponent: () => import('./pages/saglinje-statistik/saglinje-statistik').then(m => m.SaglinjeStatistikPage) },
      { path: 'klassificeringslinje/skiftrapport', loadComponent: () => import('./pages/klassificeringslinje-skiftrapport/klassificeringslinje-skiftrapport').then(m => m.KlassificeringslinjeSkiftrapportPage) },
      { path: 'klassificeringslinje/statistik', loadComponent: () => import('./pages/klassificeringslinje-statistik/klassificeringslinje-statistik').then(m => m.KlassificeringslinjeStatistikPage) },

      // Rapporter
      { path: 'rapporter/manad', canActivate: [authGuard], loadComponent: () => import('./pages/monthly-report/monthly-report').then(m => m.MonthlyReportPage) },
      { path: 'rapporter/vecka', canActivate: [authGuard], loadComponent: () => import('./pages/weekly-report/weekly-report').then(m => m.WeeklyReportPage) },

      // Authenticated routes
      { path: 'rebotling/min-dag', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/min-dag/min-dag').then(m => m.MinDagPage) },
      { path: 'rebotling/kassationsanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationsanalys/kassationsanalys').then(m => m.KassationsanalysPage) },
      { path: 'rebotling/cykeltid-heatmap', canActivate: [authGuard], loadComponent: () => import('./pages/cykeltid-heatmap/cykeltid-heatmap').then(m => m.CykeltidHeatmapComponent) },
      { path: 'rebotling/produkttyp-effektivitet', canActivate: [authGuard], loadComponent: () => import('./pages/statistik-produkttyp-effektivitet/statistik-produkttyp-effektivitet').then(m => m.StatistikProduktTypEffektivitetComponent) },
      { path: 'rebotling/alerts', canActivate: [adminGuard], loadComponent: () => import('./pages/rebotling/alerts/alerts').then(m => m.AlertsPage) },
      { path: 'min-bonus', canActivate: [authGuard], loadComponent: () => import('./pages/my-bonus/my-bonus').then(m => m.MyBonusPage) },
      { path: 'rebotling/overlamning', canActivate: [authGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/shift-handover/shift-handover').then(m => m.ShiftHandoverPage) },
      { path: 'rebotling/skiftoverlamning', canActivate: [authGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./rebotling/skiftoverlamning/skiftoverlamning.component').then(m => m.SkiftoverlamningProtokollPage) },
      { path: 'stopporsaker', canActivate: [authGuard], loadComponent: () => import('./pages/stoppage-log/stoppage-log').then(m => m.StoppageLogPage) },
      { path: 'rebotling/stopporsak-registrering', canActivate: [authGuard], loadComponent: () => import('./pages/stopporsak-registrering/stopporsak-registrering').then(m => m.StopporsakRegistreringPage) },
      { path: 'rebotling/underhallslogg', canActivate: [authGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/underhallslogg/underhallslogg').then(m => m.UnderhallsloggComponent) },
      { path: 'rebotling/oee-benchmark', canActivate: [authGuard], loadComponent: () => import('./pages/oee-benchmark/oee-benchmark').then(m => m.OeeBenchmarkComponent) },
      { path: 'rebotling/skiftrapport-export', canActivate: [authGuard], loadComponent: () => import('./pages/skiftrapport-export/skiftrapport-export').then(m => m.SkiftrapportExportComponent) },
      { path: 'rebotling/feedback-analys', canActivate: [authGuard], loadComponent: () => import('./pages/feedback-analys/feedback-analys').then(m => m.FeedbackAnalysComponent) },
      { path: 'rebotling/ranking-historik', canActivate: [authGuard], loadComponent: () => import('./pages/ranking-historik/ranking-historik').then(m => m.RankingHistorikComponent) },
      { path: 'rebotling/daglig-sammanfattning', canActivate: [authGuard], loadComponent: () => import('./pages/daglig-sammanfattning/daglig-sammanfattning').then(m => m.DagligSammanfattningComponent) },
      { path: 'rebotling/produktionskalender', canActivate: [authGuard], loadComponent: () => import('./pages/produktionskalender/produktionskalender').then(m => m.ProduktionskalenderComponent) },
      { path: 'rebotling/skiftjamforelse', canActivate: [authGuard], loadComponent: () => import('./pages/skiftjamforelse/skiftjamforelse').then(m => m.SkiftjamforelseComponent) },
      { path: 'rebotling/malhistorik', canActivate: [authGuard], loadComponent: () => import('./pages/malhistorik/malhistorik').then(m => m.MalhistorikComponent) },
      { path: 'rebotling/underhallsprognos', canActivate: [authGuard], loadComponent: () => import('./pages/underhallsprognos/underhallsprognos').then(m => m.UnderhallsprognosComponent) },
      { path: 'rebotling/effektivitet', canActivate: [authGuard], loadComponent: () => import('./pages/effektivitet/effektivitet').then(m => m.EffektivitetComponent) },
      { path: 'rebotling/produktionsmal', canActivate: [authGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/produktionsmal/produktionsmal').then(m => m.ProduktionsmalComponent) },
      { path: 'rebotling/utnyttjandegrad', canActivate: [authGuard], loadComponent: () => import('./pages/utnyttjandegrad/utnyttjandegrad').then(m => m.UtnyttjandegradComponent) },
      { path: 'rebotling/produktionstakt', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionstakt/produktionstakt').then(m => m.ProduktionsTaktPage) },
      { path: 'rebotling/veckorapport', canActivate: [authGuard], loadComponent: () => import('./pages/veckorapport/veckorapport').then(m => m.VeckorapportPage) },
      { path: 'rebotling/alarm-historik', canActivate: [authGuard], loadComponent: () => import('./pages/alarm-historik/alarm-historik').then(m => m.AlarmHistorikPage) },
      { path: 'rebotling/operatorsportal', canActivate: [authGuard], loadComponent: () => import('./pages/operatorsportal/operatorsportal').then(m => m.OperatorsportalPage) },
      { path: 'rebotling/produktions-heatmap', canActivate: [authGuard], loadComponent: () => import('./pages/heatmap/heatmap').then(m => m.HeatmapPage) },
      { path: 'rebotling/pareto', canActivate: [authGuard], loadComponent: () => import('./pages/pareto/pareto').then(m => m.ParetoPage) },
      { path: 'rebotling/oee-waterfall', canActivate: [authGuard], loadComponent: () => import('./pages/oee-waterfall/oee-waterfall').then(m => m.OeeWaterfallPage) },
      { path: 'rebotling/morgonrapport', canActivate: [authGuard], loadComponent: () => import('./pages/morgonrapport/morgonrapport').then(m => m.MorgonrapportPage) },
      { path: 'rebotling/drifttids-timeline', canActivate: [authGuard], loadComponent: () => import('./pages/drifttids-timeline/drifttids-timeline.component').then(m => m.DrifttidsTimelineComponent) },
      { path: 'rebotling/kassationsorsak-drilldown', canActivate: [authGuard], loadComponent: () => import('./pages/kassations-drilldown/kassations-drilldown').then(m => m.KassationsDrilldownPage) },
      { path: 'rebotling/forsta-timme-analys', canActivate: [authGuard], loadComponent: () => import('./pages/forsta-timme-analys/forsta-timme-analys').then(m => m.ForstaTimmeAnalysPage) },
      { path: 'rebotling/operator-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/operator-personal-dashboard/operator-personal-dashboard').then(m => m.OperatorPersonalDashboardPage) },
      { path: 'rebotling/produktionsprognos', canActivate: [authGuard], loadComponent: () => import('./pages/produktionsprognos/produktionsprognos').then(m => m.ProduktionsPrognosPage) },
      { path: 'rebotling/stopporsak-operator', canActivate: [authGuard], loadComponent: () => import('./pages/stopporsak-operator/stopporsak-operator').then(m => m.StopporsakOperatorPage) },
      { path: 'rebotling/operator-onboarding', canActivate: [authGuard], loadComponent: () => import('./pages/operator-onboarding/operator-onboarding').then(m => m.OperatorOnboardingPage) },
      { path: 'rebotling/operator-jamforelse', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/operator-jamforelse/operator-jamforelse').then(m => m.OperatorJamforelsePage) },
      { path: 'favoriter', canActivate: [authGuard], loadComponent: () => import('./pages/favoriter/favoriter').then(m => m.FavoriterPage) },
      { path: 'funktioner', canActivate: [authGuard], loadComponent: () => import('./pages/funktionshub/funktionshub').then(m => m.FunktionshubPage) },
      { path: 'rebotling/produktionseffektivitet', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionseffektivitet/produktionseffektivitet').then(m => m.ProduktionseffektivitetPage) },
      { path: 'rebotling/kvalitets-trendbrott', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kvalitets-trendbrott/kvalitets-trendbrott').then(m => m.KvalitetsTrendbrottPage) },
      { path: 'rebotling/maskinunderhall', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskinunderhall/maskinunderhall.component').then(m => m.MaskinunderhallPage) },
      { path: 'rebotling/statistik-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/statistik-dashboard/statistik-dashboard.component').then(m => m.StatistikDashboardPage) },
      { path: 'rebotling/batch-sparning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/batch-sparning/batch-sparning.component').then(m => m.BatchSparningPage) },
      { path: 'rebotling/kassationsorsak-statistik', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationsorsak-statistik/kassationsorsak-statistik').then(m => m.KassationsorsakStatistikPage) },
      { path: 'rebotling/produktions-sla', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktions-sla/produktions-sla.component').then(m => m.ProduktionsSlaPage) },
      { path: 'rebotling/skiftplanering', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/skiftplanering/skiftplanering.component').then(m => m.SkiftplaneringPage) },
      { path: 'rebotling/produktionskostnad', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionskostnad/produktionskostnad.component').then(m => m.ProduktionskostnadPage) },
      { path: 'rebotling/stopptidsanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/stopptidsanalys/stopptidsanalys.component').then(m => m.StopptidsanalysPage) },
      { path: 'rebotling/maskin-oee', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskin-oee/maskin-oee.component').then(m => m.MaskinOeePage) },
      { path: 'rebotling/operatorsbonus', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/operatorsbonus/operatorsbonus.component').then(m => m.OperatorsbonusPage) },
      { path: 'rebotling/leveransplanering', canActivate: [authGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/rebotling/leveransplanering/leveransplanering.component').then(m => m.LeveransplaneringPage) },
      { path: 'rebotling/kvalitetscertifikat', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kvalitetscertifikat/kvalitetscertifikat.component').then(m => m.KvalitetscertifikatPage) },
      { path: 'rebotling/historisk-produktion', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/historisk-produktion/historisk-produktion.component').then(m => m.HistoriskProduktionPage) },
      { path: 'rebotling/avvikelselarm', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/avvikelselarm/avvikelselarm.component').then(m => m.AvvikelselarmPage) },
      { path: 'rebotling/sammanfattning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/rebotling-sammanfattning/rebotling-sammanfattning.component').then(m => m.RebotlingSammanfattningPage) },
      { path: 'rebotling/produktionsflode', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionsflode/produktionsflode.component').then(m => m.ProduktionsflodePage) },
      { path: 'rebotling/kassationsorsak', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationsorsak/kassationsorsak').then(m => m.KassationsorsakPage) },
      { path: 'rebotling/oee-jamforelse', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/oee-jamforelse/oee-jamforelse').then(m => m.OeeJamforelsePage) },
      { path: 'rebotling/maskin-drifttid', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskin-drifttid/maskin-drifttid').then(m => m.MaskinDrifttidPage) },
      { path: 'rebotling/skiftrapport-sammanstallning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/skiftrapport-sammanstallning/skiftrapport-sammanstallning').then(m => m.SkiftrapportSammanstallningPage) },
      { path: 'rebotling/maskinhistorik', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/maskinhistorik/maskinhistorik.component').then(m => m.MaskinhistorikPage) },
      { path: 'rebotling/kassationskvot-alarm', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kassationskvot-alarm/kassationskvot-alarm.component').then(m => m.KassationskvotAlarmPage) },
      { path: 'rebotling/produktions-dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktions-dashboard/produktions-dashboard.component').then(m => m.ProduktionsDashboardPage) },
      { path: 'rebotling/kapacitetsplanering', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kapacitetsplanering/kapacitetsplanering.component').then(m => m.KapacitetsplaneringPage) },
      { path: 'rebotling/rebotling-trendanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/rebotling-trendanalys/rebotling-trendanalys.component').then(m => m.RebotlingTrendanalysPage) },
      { path: 'rebotling/operators-prestanda', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/operators-prestanda/operators-prestanda.component').then(m => m.OperatorsPrestandaPage) },
      { path: 'rebotling/stationsdetalj', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/stationsdetalj/stationsdetalj.component').then(m => m.RebotlingStationsdetaljPage) },
      { path: 'rebotling/vd-veckorapport', canActivate: [adminGuard], loadComponent: () => import('./pages/rebotling/vd-veckorapport/vd-veckorapport.component').then(m => m.VdVeckorapportPage) },
      { path: 'rebotling/stopporsaker', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/stopporsaker/stopporsaker.component').then(m => m.StopporsakerPage) },
      { path: 'rebotling/produktionsmal-uppfoljning', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/produktionsmal/produktionsmal.component').then(m => m.RebotlingProduktionsmalPage) },
      { path: 'rebotling/tidrapport', canActivate: [authGuard], loadComponent: () => import('./pages/tidrapport/tidrapport.component').then(m => m.TidrapportPage) },
      { path: 'rebotling/oee-trendanalys', canActivate: [authGuard], loadComponent: () => import('./pages/oee-trendanalys/oee-trendanalys.component').then(m => m.OeeTrendanalysPage) },
      { path: 'rebotling/operator-ranking', canActivate: [authGuard], loadComponent: () => import('./pages/operator-ranking/operator-ranking.component').then(m => m.OperatorRankingPage) },
      { path: 'rebotling/vd-dashboard', canActivate: [adminGuard], loadComponent: () => import('./pages/vd-dashboard/vd-dashboard.component').then(m => m.VdDashboardPage) },
      { path: 'rebotling/historisk-sammanfattning', canActivate: [authGuard], loadComponent: () => import('./pages/historisk-sammanfattning/historisk-sammanfattning.component').then(m => m.HistoriskSammanfattningPage) },
      { path: 'rebotling/kvalitetstrendanalys', canActivate: [authGuard], loadComponent: () => import('./pages/rebotling/kvalitetstrendanalys/kvalitetstrendanalys').then(m => m.KvalitetstrendanalysPage) },
      { path: 'rebotling/daglig-briefing', canActivate: [authGuard], loadComponent: () => import('./rebotling/daglig-briefing/daglig-briefing.component').then(m => m.DagligBriefingPage) },
      { path: 'rebotling/gamification', canActivate: [authGuard], loadComponent: () => import('./rebotling/gamification/gamification.component').then(m => m.GamificationPage) },
      { path: 'rebotling/prediktivt-underhall', canActivate: [authGuard], loadComponent: () => import('./rebotling/prediktivt-underhall/prediktivt-underhall.component').then(m => m.PrediktivtUnderhallPage) },

      // Statistik
      { path: 'statistik/overblick', canActivate: [authGuard], loadComponent: () => import('./pages/statistik-overblick/statistik-overblick.component').then(m => m.StatistikOverblickPage) },

      // Admin routes
      { path: 'oversikt', canActivate: [adminGuard], loadComponent: () => import('./pages/executive-dashboard/executive-dashboard').then(m => m.ExecutiveDashboardPage) },
      { path: 'rebotling/admin', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/rebotling-admin/rebotling-admin').then(m => m.RebotlingAdminPage) },
      { path: 'rebotling/bonus', canActivate: [adminGuard], loadComponent: () => import('./pages/bonus-dashboard/bonus-dashboard').then(m => m.BonusDashboardPage) },
      { path: 'rebotling/bonus-admin', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/bonus-admin/bonus-admin').then(m => m.BonusAdminPage) },
      { path: 'rebotling/plc-diagnostik', canActivate: [adminGuard], loadComponent: () => import('./pages/plc-diagnostik/plc-diagnostik').then(m => m.PlcDiagnostikPage) },
      { path: 'rebotling/operator-prestation', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-prestation/operator-prestation').then(m => m.OperatorPrestationPage) },
      { path: 'rebotling/operator-analys', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-analys/operator-analys').then(m => m.OperatorAnalysPage) },
      { path: 'rebotling/operator-scores', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-scores/operator-scores').then(m => m.OperatorScoresPage) },
      { path: 'rebotling/operator-matcher', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-matcher/operator-matcher').then(m => m.OperatorMatcherPage) },
      { path: 'rebotling/shift-dna', canActivate: [adminGuard], loadComponent: () => import('./pages/shift-dna/shift-dna').then(m => m.ShiftDnaPage) },
      { path: 'rebotling/operator/:number', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-profile/operator-profile').then(m => m.OperatorProfilePage) },
      { path: 'rebotling/operator-trend-heatmap', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-trend-heatmap/operator-trend-heatmap').then(m => m.OperatorTrendHeatmapPage) },
      { path: 'rebotling/team-optimizer', canActivate: [adminGuard], loadComponent: () => import('./pages/team-optimizer/team-optimizer').then(m => m.TeamOptimizerPage) },
      { path: 'rebotling/operator-monthly-report', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-monthly-report/operator-monthly-report').then(m => m.OperatorMonthlyReportPage) },
      { path: 'rebotling/operator-kvartal', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-kvartal/operator-kvartal').then(m => m.OperatorKvartalPage) },
      { path: 'rebotling/operator-performance-map', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-performance-map/operator-performance-map').then(m => m.OperatorPerformanceMapPage) },
      { path: 'rebotling/operator-aktivitet', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-aktivitet/operator-aktivitet').then(m => m.OperatorAktivitetPage) },
      { path: 'rebotling/operator-compare', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-compare/operator-compare').then(m => m.OperatorComparePage) },
      { path: 'rebotling/bonus-kalkylator', canActivate: [adminGuard], loadComponent: () => import('./pages/bonus-kalkylator/bonus-kalkylator').then(m => m.BonusKalkylatorPage) },
      { path: 'rebotling/operator-inlarning', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-inlarning/operator-inlarning').then(m => m.OperatorInlarningPage) },
      { path: 'rebotling/operator-varning', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-varning/operator-varning').then(m => m.OperatorVarningPage) },
      { path: 'rebotling/operator-produkt', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-produkt/operator-produkt').then(m => m.OperatorProduktPage) },
      { path: 'rebotling/operator-stopptid', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-stopptid/operator-stopptid').then(m => m.OperatorStopptidPage) },
      { path: 'rebotling/skift-kalender', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-kalender/skift-kalender').then(m => m.SkiftKalenderPage) },
      { path: 'rebotling/operator-veckodag', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-veckodag/operator-veckodag').then(m => m.OperatorVeckodagPage) },
      { path: 'rebotling/operator-kassation', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-kassation/operator-kassation').then(m => m.OperatorKassationPage) },
      { path: 'rebotling/skift-prognos', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-prognos/skift-prognos').then(m => m.SkiftPrognosPage) },
      { path: 'rebotling/ibc-forlust', canActivate: [adminGuard], loadComponent: () => import('./pages/ibc-forlust/ibc-forlust').then(m => m.IbcForlustPage) },
      { path: 'rebotling/operator-positioner', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-positioner/operator-positioner').then(m => m.OperatorPositionerPage) },
      { path: 'rebotling/kompetens-matris', canActivate: [adminGuard], loadComponent: () => import('./pages/kompetens-matris/kompetens-matris').then(m => m.KompetensMatrisPage) },
      { path: 'rebotling/operator-synergy', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-synergy/operator-synergy').then(m => m.OperatorSynergyPage) },
      { path: 'rebotling/skift-topplista', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-topplista/skift-topplista').then(m => m.SkiftTopplista) },
      { path: 'rebotling/produktion-heatmap', canActivate: [adminGuard], loadComponent: () => import('./pages/produktion-heatmap/produktion-heatmap').then(m => m.ProduktionHeatmapPage) },
      { path: 'rebotling/operator-skifttyp', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-skifttyp/operator-skifttyp').then(m => m.OperatorSkifttypPage) },
      { path: 'rebotling/operator-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-trend/operator-trend').then(m => m.OperatorTrendPage) },
      { path: 'rebotling/rekord-statistik', canActivate: [adminGuard], loadComponent: () => import('./pages/rekord-statistik/rekord-statistik').then(m => m.RekordStatistikPage) },
      { path: 'rebotling/skiftlag-historik', canActivate: [adminGuard], loadComponent: () => import('./pages/skiftlag-historik/skiftlag-historik').then(m => m.SkiftlagHistorikPage) },
      { path: 'rebotling/operator-momentum', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-momentum/operator-momentum').then(m => m.OperatorMomentumPage) },
      { path: 'rebotling/operator-konsistens', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-konsistens/operator-konsistens').then(m => m.OperatorKonsistensPage) },
      { path: 'rebotling/produkt-analys', canActivate: [adminGuard], loadComponent: () => import('./pages/produkt-analys/produkt-analys').then(m => m.ProduktAnalysPage) },
      { path: 'rebotling/veckans-topplista', canActivate: [adminGuard], loadComponent: () => import('./pages/veckans-topplista/veckans-topplista').then(m => m.VeckansTopplista) },
      { path: 'rebotling/operator-avsaknad', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-avsaknad/operator-avsaknad').then(m => m.OperatorAvsaknadPage) },
      { path: 'rebotling/kassations-karta', canActivate: [adminGuard], loadComponent: () => import('./pages/kassations-karta/kassations-karta').then(m => m.KassationsKartaPage) },
      { path: 'rebotling/kassation-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/kassation-trend/kassation-trend').then(m => m.KassationTrendPage) },
      { path: 'rebotling/kassationsorsak-per-operator', canActivate: [adminGuard], loadComponent: () => import('./pages/kassationsorsak-per-operator/kassationsorsak-per-operator').then(m => m.KassationsorsakPerOperatorPage) },
      { path: 'rebotling/kassationsorsak-per-produkt', canActivate: [adminGuard], loadComponent: () => import('./pages/kassationsorsak-per-produkt/kassationsorsak-per-produkt').then(m => m.KassationsorsakPerProduktPage) },
      { path: 'rebotling/kassationsorsak-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/kassationsorsak-trend/kassationsorsak-trend').then(m => m.KassationsorsakTrendPage) },
      { path: 'rebotling/stopp-per-produkt', canActivate: [adminGuard], loadComponent: () => import('./pages/stopp-per-produkt/stopp-per-produkt').then(m => m.StoppPerProduktPage) },
      { path: 'rebotling/coach-view', canActivate: [adminGuard], loadComponent: () => import('./pages/tranar-vy/tranar-vy').then(m => m.TranarVyPage) },
      { path: 'rebotling/produktions-tidsserie', canActivate: [adminGuard], loadComponent: () => import('./pages/produktions-tidsserie/produktions-tidsserie').then(m => m.ProduktionsTidsseriePage) },
      { path: 'rebotling/skift-insikt', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-insikt/skift-insikt').then(m => m.SkiftInsiktPage) },
      { path: 'rebotling/rast-analys', canActivate: [adminGuard], loadComponent: () => import('./pages/rast-analys/rast-analys').then(m => m.RastAnalysPage) },
      { path: 'rebotling/sasongsanalys', canActivate: [adminGuard], loadComponent: () => import('./pages/sasongsanalys/sasongsanalys').then(m => m.SasongsanalysPage) },
      { path: 'rebotling/produktionsrytm', canActivate: [adminGuard], loadComponent: () => import('./pages/produktionsrytm/produktionsrytm').then(m => m.ProduktionsrytmPage) },
      { path: 'rebotling/fart-kvalitet', canActivate: [adminGuard], loadComponent: () => import('./pages/fart-kvalitet/fart-kvalitet').then(m => m.FartKvalitetPage) },
      { path: 'rebotling/stopptidsmonster', canActivate: [adminGuard], loadComponent: () => import('./pages/stopptidsmonster/stopptidsmonster').then(m => m.StopptidsmönsterPage) },
      { path: 'rebotling/fart-produkt-matris', canActivate: [adminGuard], loadComponent: () => import('./pages/fart-produkt-matris/fart-produkt-matris').then(m => m.FartProduktMatrisPage) },
      { path: 'rebotling/fart-stopp', canActivate: [adminGuard], loadComponent: () => import('./pages/fart-stopp/fart-stopp').then(m => m.FartStoppPage) },
      { path: 'rebotling/kassation-stopp', canActivate: [adminGuard], loadComponent: () => import('./pages/kassation-stopp/kassation-stopp').then(m => m.KassationStoppPage) },
      { path: 'rebotling/kassationsrytm', canActivate: [adminGuard], loadComponent: () => import('./pages/kassationsrytm/kassationsrytm').then(m => m.KassationsrytmPage) },
      { path: 'rebotling/kassationsbudget', canActivate: [adminGuard], loadComponent: () => import('./pages/kassationsbudget/kassationsbudget').then(m => m.KassationsbudgetPage) },
      { path: 'rebotling/stopptidsbudget', canActivate: [adminGuard], loadComponent: () => import('./pages/stopptidsbudget/stopptidsbudget').then(m => m.StopptidsbudgetPage) },
      { path: 'rebotling/operator-rotation', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-rotation/operator-rotation').then(m => m.OperatorRotationPage) },
      { path: 'rebotling/manads-jamforelse', canActivate: [adminGuard], loadComponent: () => import('./pages/manads-jamforelse/manads-jamforelse').then(m => m.ManadsJamforelsePage) },
      { path: 'rebotling/skifttyps-matris', canActivate: [adminGuard], loadComponent: () => import('./pages/skifttyps-matris/skifttyps-matris').then(m => m.SkifttypsMatrisPage) },
      { path: 'rebotling/kassationstyper', canActivate: [adminGuard], loadComponent: () => import('./pages/kassationstyper/kassationstyper').then(m => m.KassationstyperPage) },
      { path: 'rebotling/positions-specialisering', canActivate: [adminGuard], loadComponent: () => import('./pages/positions-specialisering/positions-specialisering').then(m => m.PositionsSpecialiseringPage) },
      { path: 'rebotling/korstraning', canActivate: [adminGuard], loadComponent: () => import('./pages/korstraning/korstraning').then(m => m.KorstraningPage) },
      { path: 'rebotling/idag', canActivate: [adminGuard], loadComponent: () => import('./pages/idag/idag').then(m => m.IdagPage) },
      { path: 'rebotling/skift-logg', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-logg/skift-logg').then(m => m.SkiftLoggPage) },
      { path: 'rebotling/skift-avvikelser', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-avvikelser/skift-avvikelser').then(m => m.SkiftAvvikelserPage) },
      { path: 'rebotling/stjarnoperatorer', canActivate: [adminGuard], loadComponent: () => import('./pages/stjarnoperatorer/stjarnoperatorer').then(m => m.StjarnoperatororPage) },
      { path: 'rebotling/produkt-kvalitetstrender', canActivate: [adminGuard], loadComponent: () => import('./pages/produkt-kvalitetstrender/produkt-kvalitetstrender').then(m => m.ProduktKvalitetstrender) },
      { path: 'rebotling/maskinpark-analys', canActivate: [adminGuard], loadComponent: () => import('./pages/maskinpark-analys/maskinpark-analys').then(m => m.MaskinparkAnalysPage) },
      { path: 'rebotling/milstolpar', canActivate: [adminGuard], loadComponent: () => import('./pages/milstolpar/milstolpar').then(m => m.MilstolparPage) },
      { path: 'rebotling/produkt-normaliserad', canActivate: [adminGuard], loadComponent: () => import('./pages/produkt-normaliserad/produkt-normaliserad').then(m => m.ProduktNormaliseradPage) },
      { path: 'rebotling/ars-kurva', canActivate: [adminGuard], loadComponent: () => import('./pages/ars-kurva/ars-kurva').then(m => m.ArsKurvaPage) },
      { path: 'rebotling/schema-rekommendationer', canActivate: [adminGuard], loadComponent: () => import('./pages/schema-rekommendationer/schema-rekommendationer').then(m => m.SchemaRekommendationerPage) },
      { path: 'rebotling/produktbyten', canActivate: [adminGuard], loadComponent: () => import('./pages/produktbyten/produktbyten').then(m => m.ProduktbytenPage) },
      { path: 'rebotling/tacknings-analys', canActivate: [adminGuard], loadComponent: () => import('./pages/tacknings-analys/tacknings-analys').then(m => m.TackningsAnalysPage) },
      { path: 'rebotling/vader-produktion', canActivate: [adminGuard], loadComponent: () => import('./pages/vader-produktion/vader-produktion').then(m => m.VaderProduktionPage) },
      { path: 'rebotling/belastningsbalans', canActivate: [adminGuard], loadComponent: () => import('./pages/belastningsbalans/belastningsbalans').then(m => m.BelastningsbalansPage) },
      { path: 'rebotling/personal-kalender', canActivate: [adminGuard], loadComponent: () => import('./pages/personal-kalender/personal-kalender').then(m => m.PersonalKalenderPage) },
      { path: 'rebotling/skift-sekvens', canActivate: [adminGuard], loadComponent: () => import('./pages/skift-sekvens/skift-sekvens').then(m => m.SkiftSekvensPage) },
      { path: 'rebotling/produktionsmaal', canActivate: [adminGuard], loadComponent: () => import('./pages/produktionsmaal/produktionsmaal').then(m => m.ProduktionsmaalPage) },
      { path: 'rebotling/operator-utveckling', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-utveckling/operator-utveckling').then(m => m.OperatorUtvecklingPage) },
      { path: 'rebotling/operatormaal', canActivate: [adminGuard], loadComponent: () => import('./pages/operatormaal/operatormaal').then(m => m.OperatormaalPage) },
      { path: 'rebotling/veckosammanfattning', canActivate: [adminGuard], loadComponent: () => import('./pages/veckosammanfattning/veckosammanfattning').then(m => m.VeckosammanfattningPage) },
      { path: 'rebotling/produkt-jamforelse', canActivate: [adminGuard], loadComponent: () => import('./pages/produkt-jamforelse/produkt-jamforelse').then(m => m.ProduktJamforelsePage) },
      { path: 'rebotling/produkt-prognos', canActivate: [adminGuard], loadComponent: () => import('./pages/produkt-prognos/produkt-prognos').then(m => m.ProduktPrognosPage) },
      { path: 'rebotling/oee-dashboard', canActivate: [adminGuard], loadComponent: () => import('./pages/oee-dashboard/oee-dashboard').then(m => m.OEEDashboardPage) },
      { path: 'rebotling/analys', canActivate: [adminGuard], loadComponent: () => import('./pages/production-analysis/production-analysis').then(m => m.ProductionAnalysisPage) },
      { path: 'rebotling/kalender', canActivate: [adminGuard], loadComponent: () => import('./pages/production-calendar/production-calendar').then(m => m.ProductionCalendarPage) },
      { path: 'rebotling/prognos', canActivate: [adminGuard], loadComponent: () => import('./pages/rebotling-prognos/rebotling-prognos').then(m => m.RebotlingPrognosPage) },
      { path: 'tvattlinje/plc-diagnostik', canActivate: [adminGuard], loadComponent: () => import('./pages/tvattlinje-plc-diagnostik/tvattlinje-plc-diagnostik').then(m => m.TvattlinjePlcDiagnostikPage) },
      { path: 'tvattlinje/admin', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/tvattlinje-admin/tvattlinje-admin').then(m => m.TvattlinjeAdminPage) },
      { path: 'saglinje/admin', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/saglinje-admin/saglinje-admin').then(m => m.SaglinjeAdminPage) },
      { path: 'klassificeringslinje/admin', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/klassificeringslinje-admin/klassificeringslinje-admin').then(m => m.KlassificeringslinjeAdminPage) },
      { path: 'admin/users', canActivate: [adminGuard], loadComponent: () => import('./pages/users/users').then(m => m.UsersPage) },
      { path: 'admin/create-user', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/create-user/create-user').then(m => m.CreateUserPage) },
      { path: 'admin/vpn', canActivate: [adminGuard], loadComponent: () => import('./pages/vpn-admin/vpn-admin').then(m => m.VpnAdminPage) },
      { path: 'admin/audit', canActivate: [adminGuard], loadComponent: () => import('./pages/audit-log/audit-log').then(m => m.AuditLogPage) },
      { path: 'admin/news', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/news-admin/news-admin').then(m => m.NewsAdminPage) },
      { path: 'admin/operators', canActivate: [adminGuard], loadComponent: () => import('./pages/operators/operators').then(m => m.OperatorsPage) },
      { path: 'admin/skiftplan', canActivate: [adminGuard], loadComponent: () => import('./pages/shift-plan/shift-plan').then(m => m.ShiftPlanPage) },
      { path: 'admin/certifiering', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/certifications/certifications').then(m => m.CertificationsPage) },
      { path: 'admin/operator-dashboard', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-dashboard/operator-dashboard').then(m => m.OperatorDashboardPage) },
      { path: 'admin/operator-compare', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-compare/operator-compare').then(m => m.OperatorComparePage) },
      { path: 'admin/operator-attendance', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-attendance/operator-attendance').then(m => m.OperatorAttendancePage) },
      { path: 'admin/operator-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-trend/operator-trend').then(m => m.OperatorTrendPage) },
      { path: 'admin/kvalitetstrend', canActivate: [adminGuard], loadComponent: () => import('./pages/kvalitetstrend/kvalitetstrend').then(m => m.KvalitetstrendComponent) },
      { path: 'admin/stopporsak-trend', canActivate: [adminGuard], loadComponent: () => import('./pages/stopporsak-trend/stopporsak-trend').then(m => m.StopporsakTrendComponent) },
      { path: 'admin/operator/:id', canActivate: [adminGuard], loadComponent: () => import('./pages/operator-detail/operator-detail').then(m => m.OperatorDetailPage) },
      { path: 'admin/underhall', canActivate: [adminGuard], loadComponent: () => import('./pages/maintenance-log/maintenance-log').then(m => m.MaintenanceLogPage) },
      { path: 'admin/feature-flags', canActivate: [adminGuard], canDeactivate: [pendingChangesGuard], loadComponent: () => import('./pages/feature-flag-admin/feature-flag-admin').then(m => m.FeatureFlagAdminPage) },

      { path: 'rebotling/andon', canActivate: [authGuard], loadComponent: () => import('./pages/andon/andon').then(m => m.AndonPage) },
      { path: 'rebotling/andon-board', canActivate: [authGuard], loadComponent: () => import('./pages/andon-board/andon-board').then(m => m.AndonBoardComponent) },
      { path: '**', loadComponent: () => import('./pages/not-found/not-found').then(m => m.NotFoundPage) }
    ]
  }
];
