-- Migration: Developer role + Feature flags system
-- Datum: 2026-03-14

-- 1. Ny role-kolumn på users (behåll admin-kolumnen för bakåtkompatibilitet)
ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'user' AFTER admin;
UPDATE users SET role = 'admin' WHERE admin = 1;
UPDATE users SET role = 'user' WHERE admin = 0 OR admin IS NULL;

-- 2. Feature flags tabell
CREATE TABLE IF NOT EXISTS feature_flags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    feature_key VARCHAR(100) NOT NULL UNIQUE,
    label VARCHAR(200) NOT NULL,
    category VARCHAR(50) DEFAULT 'rebotling',
    min_role ENUM('public','user','admin','developer') NOT NULL DEFAULT 'developer',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Seed: Alla menylänkar
-- Rollhierarki: public(0) < user(1) < admin(2) < developer(3)
-- Default: Live + Skiftrapport = public, resten = developer
INSERT INTO feature_flags (feature_key, label, category, min_role) VALUES
-- Rebotling: public (alla ser)
('rebotling/live', 'Live', 'rebotling', 'public'),
('rebotling/live-ranking', 'Live Ranking', 'rebotling', 'public'),
('rebotling/skiftrapport', 'Skiftrapport', 'rebotling', 'public'),
('rebotling/statistik', 'Statistik', 'rebotling', 'public'),
('rebotling/historik', 'Historisk jämförelse', 'rebotling', 'public'),
('rebotling/andon', 'Andon-tavla', 'rebotling', 'public'),
('rebotling/andon-board', 'Fabriksskärm', 'rebotling', 'public'),

-- Rebotling: developer (dolt default)
('rebotling/produktions-dashboard', 'Produktions-dashboard', 'rebotling', 'developer'),
('rebotling/sammanfattning', 'Sammanfattning', 'rebotling', 'developer'),
('rebotling/kassationsanalys', 'Kassationsanalys', 'rebotling', 'developer'),
('rebotling/kassationsorsak-drilldown', 'Kassationsanalys+', 'rebotling', 'developer'),
('rebotling/cykeltid-heatmap', 'Cykeltids-heatmap', 'rebotling', 'developer'),
('rebotling/produkttyp-effektivitet', 'Produkttyp-effektivitet', 'rebotling', 'developer'),
('rebotling/narvarotracker', 'Närvarotracker', 'rebotling', 'developer'),
('rebotling/produktionspuls', 'Produktionspuls', 'rebotling', 'developer'),
('rebotling/produktionstakt', 'Produktionstakt', 'rebotling', 'developer'),
('rebotling/benchmarking', 'Benchmarking', 'rebotling', 'developer'),
('rebotling/overlamning', 'Skiftöverlämning', 'rebotling', 'developer'),
('rebotling/skiftoverlamning', 'Skiftoverlamning', 'rebotling', 'developer'),
('rebotling/operatorsportal', 'Min portal', 'rebotling', 'developer'),
('rebotling/min-dag', 'Min dag', 'rebotling', 'developer'),
('rebotling/operator-dashboard', 'Min statistik', 'rebotling', 'developer'),
('min-bonus', 'Min Bonus', 'rebotling', 'developer'),
('rebotling/stopporsak-registrering', 'Registrera stopp', 'rebotling', 'developer'),
('rebotling/underhallslogg', 'Underhållslogg', 'rebotling', 'developer'),
('rebotling/stopporsaker', 'Stopporsak-dashboard', 'rebotling', 'developer'),
('rebotling/oee-benchmark', 'OEE Benchmark', 'rebotling', 'developer'),
('rebotling/skiftrapport-export', 'Skiftrapport PDF', 'rebotling', 'developer'),
('rebotling/feedback-analys', 'Feedback-analys', 'rebotling', 'developer'),
('rebotling/ranking-historik', 'Ranking-historik', 'rebotling', 'developer'),
('rebotling/daglig-sammanfattning', 'Daglig sammanfattning', 'rebotling', 'developer'),
('rebotling/produktionskalender', 'Produktionskalender', 'rebotling', 'developer'),
('rebotling/skiftjamforelse', 'Skiftjämförelse', 'rebotling', 'developer'),
('rebotling/malhistorik', 'Målhistorik', 'rebotling', 'developer'),
('rebotling/underhallsprognos', 'Underhållsprognos', 'rebotling', 'developer'),
('rebotling/prediktivt-underhall', 'Prediktivt underhåll', 'rebotling', 'developer'),
('rebotling/effektivitet', 'Maskineffektivitet', 'rebotling', 'developer'),
('rebotling/produktionsmal', 'Produktionsmål', 'rebotling', 'developer'),
('rebotling/utnyttjandegrad', 'Utnyttjandegrad', 'rebotling', 'developer'),
('rebotling/daglig-briefing', 'Daglig briefing', 'rebotling', 'developer'),
('rebotling/morgonrapport', 'Morgonrapport', 'rebotling', 'developer'),
('rebotling/veckorapport', 'Veckorapport', 'rebotling', 'developer'),
('rebotling/alarm-historik', 'Alarm-historik', 'rebotling', 'developer'),
('rebotling/pareto', 'Pareto-analys', 'rebotling', 'developer'),
('rebotling/produktions-heatmap', 'Produktions-heatmap', 'rebotling', 'developer'),
('rebotling/oee-waterfall', 'OEE-analys', 'rebotling', 'developer'),
('rebotling/drifttids-timeline', 'Drifttids-timeline', 'rebotling', 'developer'),
('rebotling/forsta-timme-analys', 'Första timmen', 'rebotling', 'developer'),
('rebotling/produktionsprognos', 'Produktionsprognos', 'rebotling', 'developer'),
('rebotling/stopporsak-operator', 'Stopporsak per operatör', 'rebotling', 'developer'),
('rebotling/operator-onboarding', 'Operator-onboarding', 'rebotling', 'developer'),
('rebotling/operator-jamforelse', 'Operatörsjämförelse', 'rebotling', 'developer'),
('rebotling/produktionseffektivitet', 'Produktionseffektivitet/h', 'rebotling', 'developer'),
('rebotling/kvalitets-trendbrott', 'Kvalitets-trendbrott', 'rebotling', 'developer'),
('rebotling/maskinunderhall', 'Maskinunderhåll', 'rebotling', 'developer'),
('rebotling/statistik-dashboard', 'Statistik-dashboard', 'rebotling', 'developer'),
('rebotling/batch-sparning', 'Batch-spårning', 'rebotling', 'developer'),
('rebotling/kassationsorsak-statistik', 'Kassationsorsak-statistik', 'rebotling', 'developer'),
('rebotling/produktions-sla', 'Måluppfyllnad', 'rebotling', 'developer'),
('rebotling/skiftplanering', 'Skiftplanering', 'rebotling', 'developer'),
('rebotling/produktionskostnad', 'Produktionskostnad/IBC', 'rebotling', 'developer'),
('rebotling/stopptidsanalys', 'Stopptidsanalys', 'rebotling', 'developer'),
('rebotling/maskin-oee', 'Maskin-OEE', 'rebotling', 'developer'),
('rebotling/operatorsbonus', 'Operatörsbonus', 'rebotling', 'developer'),
('rebotling/leveransplanering', 'Leveransplanering', 'rebotling', 'developer'),
('rebotling/kvalitetscertifikat', 'Kvalitetscertifikat', 'rebotling', 'developer'),
('rebotling/historisk-produktion', 'Historisk produktion', 'rebotling', 'developer'),
('rebotling/avvikelselarm', 'Avvikelselarm', 'rebotling', 'developer'),
('rebotling/produktionsflode', 'Produktionsflöde', 'rebotling', 'developer'),
('rebotling/kassationsorsak', 'Kassationsorsak per station', 'rebotling', 'developer'),
('rebotling/oee-jamforelse', 'OEE-jämförelse', 'rebotling', 'developer'),
('rebotling/maskin-drifttid', 'Maskin-drifttid heatmap', 'rebotling', 'developer'),
('rebotling/skiftrapport-sammanstallning', 'Skiftsammanställning', 'rebotling', 'developer'),
('rebotling/maskinhistorik', 'Maskinhistorik per station', 'rebotling', 'developer'),
('rebotling/kassationskvot-alarm', 'Kassationskvot-alarm', 'rebotling', 'developer'),
('rebotling/kapacitetsplanering', 'Kapacitetsplanering', 'rebotling', 'developer'),
('rebotling/rebotling-trendanalys', 'Trendanalys', 'rebotling', 'developer'),
('rebotling/operators-prestanda', 'Operatörs-prestanda', 'rebotling', 'developer'),
('rebotling/stationsdetalj', 'Stationsdetalj', 'rebotling', 'developer'),
('rebotling/vd-veckorapport', 'VD Veckorapport', 'rebotling', 'developer'),
('rebotling/produktionsmal-uppfoljning', 'Produktionsmål-uppföljning', 'rebotling', 'developer'),
('rebotling/tidrapport', 'Tidrapport', 'rebotling', 'developer'),
('rebotling/oee-trendanalys', 'OEE Trendanalys', 'rebotling', 'developer'),
('rebotling/operator-ranking', 'Operatörsranking', 'rebotling', 'developer'),
('rebotling/gamification', 'Gamification', 'rebotling', 'developer'),
('rebotling/vd-dashboard', 'VD Dashboard', 'rebotling', 'developer'),
('rebotling/historisk-sammanfattning', 'Historisk sammanfattning', 'rebotling', 'developer'),
('rebotling/kvalitetstrendanalys', 'Kvalitetstrend-analys', 'rebotling', 'developer'),

-- Rebotling admin
('rebotling/admin', 'Rebotling Admin', 'rebotling-admin', 'admin'),
('rebotling/bonus', 'Bonus', 'rebotling-admin', 'developer'),
('rebotling/bonus-admin', 'Bonus Admin', 'rebotling-admin', 'developer'),
('rebotling/analys', 'Produktionsanalys', 'rebotling-admin', 'developer'),
('rebotling/kalender', 'Produktionskalender (Admin)', 'rebotling-admin', 'developer'),
('rebotling/prognos', 'Leveransprognos', 'rebotling-admin', 'developer'),

-- Övriga linjer (public)
('tvattlinje/live', 'Tvättlinje Live', 'tvattlinje', 'public'),
('tvattlinje/skiftrapport', 'Tvättlinje Skiftrapport', 'tvattlinje', 'public'),
('tvattlinje/statistik', 'Tvättlinje Statistik', 'tvattlinje', 'public'),
('tvattlinje/admin', 'Tvättlinje Admin', 'tvattlinje', 'admin'),
('saglinje/live', 'Såglinje Live', 'saglinje', 'public'),
('saglinje/skiftrapport', 'Såglinje Skiftrapport', 'saglinje', 'public'),
('saglinje/statistik', 'Såglinje Statistik', 'saglinje', 'public'),
('saglinje/admin', 'Såglinje Admin', 'saglinje', 'admin'),
('klassificeringslinje/live', 'Klassificeringslinje Live', 'klassificeringslinje', 'public'),
('klassificeringslinje/skiftrapport', 'Klassificeringslinje Skiftrapport', 'klassificeringslinje', 'public'),
('klassificeringslinje/statistik', 'Klassificeringslinje Statistik', 'klassificeringslinje', 'public'),
('klassificeringslinje/admin', 'Klassificeringslinje Admin', 'klassificeringslinje', 'admin'),

-- Favoriter, rapporter
('favoriter', 'Favoriter', 'system', 'developer'),
('statistik/overblick', 'Statistik-överblick', 'rapporter', 'developer'),
('rapporter/manad', 'Månadsrapport', 'rapporter', 'developer'),
('rapporter/vecka', 'Veckorapport (Rapporter)', 'rapporter', 'developer'),

-- Admin-sidor
('oversikt', 'Översikt (Executive)', 'admin', 'admin'),
('rebotling/alerts', 'Varningar', 'admin', 'developer'),
('stopporsaker', 'Stopporsaker', 'admin', 'developer'),
('admin/users', 'Användare', 'admin', 'admin'),
('admin/create-user', 'Skapa användare', 'admin', 'admin'),
('admin/operators', 'Operatörer', 'admin', 'developer'),
('admin/skiftplan', 'Skiftplan', 'admin', 'developer'),
('admin/certifiering', 'Certifiering', 'admin', 'developer'),
('admin/operator-dashboard', 'Operatörsdashboard', 'admin', 'developer'),
('admin/operator-compare', 'Operatörsjämförelse (Admin)', 'admin', 'developer'),
('admin/operator-attendance', 'Närvaro', 'admin', 'developer'),
('admin/operator-trend', 'Prestanda-trend', 'admin', 'developer'),
('admin/kvalitetstrend', 'Kvalitetstrend (Admin)', 'admin', 'developer'),
('admin/stopporsak-trend', 'Stopporsak-trend', 'admin', 'developer'),
('admin/underhall', 'Underhållslogg (Admin)', 'admin', 'developer'),
('admin/vpn', 'VPN', 'admin', 'developer'),
('admin/audit', 'Aktivitetslogg', 'admin', 'developer'),
('admin/news', 'Nyheter', 'admin', 'developer'),
('admin/feature-flags', 'Funktionshantering', 'admin', 'developer')
ON DUPLICATE KEY UPDATE label = VALUES(label);
